version: '3'

volumes:
  postgres_data:
    driver: local

services:
  keycloak:
    container_name: "keycloak"
    build: .
    environment:
      ENV: "DEV"
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DEBUG: "true"
      DEBUG_PORT: "*:8787"
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8080:8080
      - 8787:8787
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    container_name: "keycloak-db"
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
